/*
  This model will combine all of the blockgroup data for Philadelphia into a
  single table (Philadelphia has a `county_fips_code` of 101). The table should
  have the following fields:

  - geo_id
  - year
  - total_pop
  - pop_density
  - male_pop
  - female_pop
  - white_pop
  - black_pop
  - asian_pop
  - hispanic_pop
  - amerindian_pop
  - other_race_pop
  - two_or_more_races_pop
  - blockgroup_geom
  - blockgroup_key

  The model generated by this query should contain all the fields that pertain
  to blockgroups that we actually use downstream of the model. Additionally, a
  should always have some unique identifier for each record. In this case that
  will be the `blockgroup_key`, and can be made up of the `geo_id` and the
  `year`.

  The table should include data from 2010 until 2018.

  HINT: Construct a query for one year's data appropriately, and then copy/paste
  that for other years, and UNION ALL them together.
*/
SELECT gb.geo_id,
    '2010' as year,
    c.total_pop,
    c.total_pop / ST_AREA(gb.blockgroup_geom) AS pop_density,
    c.male_pop,
    c.female_pop,
    c.white_pop,
    c.black_pop,
    c.asian_pop,
    c.hispanic_pop,
    c.amerindian_pop,
    c.other_race_pop,
    c.two_or_more_races_pop,
    gb.blockgroup_geom,
    gb.geo_id || '_2010' as blockgroup_key
  FROM `bigquery-public-data.geo_census_blockgroups.blockgroups_42` as gb
  JOIN `bigquery-public-data.census_bureau_acs.blockgroup_2010_5yr` as c
  ON gb.geo_id = c.geo_id
  WHERE gb.county_fips_code='101'
  UNION ALL
  SELECT gb.geo_id,
    '2011' as year,
    c.total_pop,
    c.total_pop / ST_AREA(gb.blockgroup_geom) AS pop_density,
    c.male_pop,
    c.female_pop,
    c.white_pop,
    c.black_pop,
    c.asian_pop,
    c.hispanic_pop,
    c.amerindian_pop,
    c.other_race_pop,
    c.two_or_more_races_pop,
    gb.blockgroup_geom,
    gb.geo_id || '_2011' as blockgroup_key
  FROM `bigquery-public-data.geo_census_blockgroups.blockgroups_42` as gb
  JOIN `bigquery-public-data.census_bureau_acs.blockgroup_2011_5yr` as c
  ON gb.geo_id = c.geo_id
  WHERE gb.county_fips_code='101'
    UNION ALL
  SELECT gb.geo_id,
    '2012' as year,
    c.total_pop,
    c.total_pop / ST_AREA(gb.blockgroup_geom) AS pop_density,
    c.male_pop,
    c.female_pop,
    c.white_pop,
    c.black_pop,
    c.asian_pop,
    c.hispanic_pop,
    c.amerindian_pop,
    c.other_race_pop,
    c.two_or_more_races_pop,
    gb.blockgroup_geom,
    gb.geo_id || '_2012' as blockgroup_key
  FROM `bigquery-public-data.geo_census_blockgroups.blockgroups_42` as gb
  JOIN `bigquery-public-data.census_bureau_acs.blockgroup_2012_5yr` as c
  ON gb.geo_id = c.geo_id
  WHERE gb.county_fips_code='101'
    UNION ALL
  SELECT gb.geo_id,
    '2013' as year,
    c.total_pop,
    c.total_pop / ST_AREA(gb.blockgroup_geom) AS pop_density,
    c.male_pop,
    c.female_pop,
    c.white_pop,
    c.black_pop,
    c.asian_pop,
    c.hispanic_pop,
    c.amerindian_pop,
    c.other_race_pop,
    c.two_or_more_races_pop,
    gb.blockgroup_geom,
    gb.geo_id || '_2013' as blockgroup_key
  FROM `bigquery-public-data.geo_census_blockgroups.blockgroups_42` as gb
  JOIN `bigquery-public-data.census_bureau_acs.blockgroup_2013_5yr` as c
  ON gb.geo_id = c.geo_id
  WHERE gb.county_fips_code='101'
    UNION ALL
  SELECT gb.geo_id,
    '2014' as year,
    c.total_pop,
    c.total_pop / ST_AREA(gb.blockgroup_geom) AS pop_density,
    c.male_pop,
    c.female_pop,
    c.white_pop,
    c.black_pop,
    c.asian_pop,
    c.hispanic_pop,
    c.amerindian_pop,
    c.other_race_pop,
    c.two_or_more_races_pop,
    gb.blockgroup_geom,
    gb.geo_id || '_2014' as blockgroup_key
  FROM `bigquery-public-data.geo_census_blockgroups.blockgroups_42` as gb
  JOIN `bigquery-public-data.census_bureau_acs.blockgroup_2014_5yr` as c
  ON gb.geo_id = c.geo_id
  WHERE gb.county_fips_code='101'
    UNION ALL
  SELECT gb.geo_id,
    '2015' as year,
    c.total_pop,
    c.total_pop / ST_AREA(gb.blockgroup_geom) AS pop_density,
    c.male_pop,
    c.female_pop,
    c.white_pop,
    c.black_pop,
    c.asian_pop,
    c.hispanic_pop,
    c.amerindian_pop,
    c.other_race_pop,
    c.two_or_more_races_pop,
    gb.blockgroup_geom,
    gb.geo_id || '_2015' as blockgroup_key
  FROM `bigquery-public-data.geo_census_blockgroups.blockgroups_42` as gb
  JOIN `bigquery-public-data.census_bureau_acs.blockgroup_2015_5yr` as c
  ON gb.geo_id = c.geo_id
  WHERE gb.county_fips_code='101'
    UNION ALL
  SELECT gb.geo_id,
    '2016' as year,
    c.total_pop,
    c.total_pop / ST_AREA(gb.blockgroup_geom) AS pop_density,
    c.male_pop,
    c.female_pop,
    c.white_pop,
    c.black_pop,
    c.asian_pop,
    c.hispanic_pop,
    c.amerindian_pop,
    c.other_race_pop,
    c.two_or_more_races_pop,
    gb.blockgroup_geom,
    gb.geo_id || '_2016' as blockgroup_key
  FROM `bigquery-public-data.geo_census_blockgroups.blockgroups_42` as gb
  JOIN `bigquery-public-data.census_bureau_acs.blockgroup_2016_5yr` as c
  ON gb.geo_id = c.geo_id
  WHERE gb.county_fips_code='101'
    UNION ALL
  SELECT gb.geo_id,
    '2017' as year,
    c.total_pop,
    c.total_pop / ST_AREA(gb.blockgroup_geom) AS pop_density,
    c.male_pop,
    c.female_pop,
    c.white_pop,
    c.black_pop,
    c.asian_pop,
    c.hispanic_pop,
    c.amerindian_pop,
    c.other_race_pop,
    c.two_or_more_races_pop,
    gb.blockgroup_geom,
    gb.geo_id || '_2017' as blockgroup_key
  FROM `bigquery-public-data.geo_census_blockgroups.blockgroups_42` as gb
  JOIN `bigquery-public-data.census_bureau_acs.blockgroup_2017_5yr` as c
  ON gb.geo_id = c.geo_id
  WHERE gb.county_fips_code='101'
    UNION ALL
  SELECT gb.geo_id,
    '2018' as year,
    c.total_pop,
    c.total_pop / ST_AREA(gb.blockgroup_geom) AS pop_density,
    c.male_pop,
    c.female_pop,
    c.white_pop,
    c.black_pop,
    c.asian_pop,
    c.hispanic_pop,
    c.amerindian_pop,
    c.other_race_pop,
    c.two_or_more_races_pop,
    gb.blockgroup_geom,
    gb.geo_id || '_2018' as blockgroup_key
  FROM `bigquery-public-data.geo_census_blockgroups.blockgroups_42` as gb
  JOIN `bigquery-public-data.census_bureau_acs.blockgroup_2018_5yr` as c
  ON gb.geo_id = c.geo_id
  WHERE gb.county_fips_code='101'